### ISSUE TITLE
Warning: Could not parse Compiler option: -FS

### ISSUE THREAD

**Issue by mwpowellhtx** [commontk/qt-easy-build#13]
From the command line, received numerous warnings:

`WARNING: Could not parse Compiler option: -FS, added as AdditionalOption`

Don't know if this is anything to be concerned over.

Building with VS2013 Update 5.

**Comment by jcfr** [comment]
Thanks for the report.

This is probably a bug in the Qt build system.

Consider Qt 5 is the version actively maintained, similarly to #14 I would also suggest to ignore.
