### ISSUE TITLE
Problem building Qt! Please Help!

### ISSUE THREAD

**Issue by GuoJiechang** [commontk/qt-easy-build#18]
Hi, I'm a Chinese green hand poor english student. My task is to build the 3D slicer so that I can use the open source to program. I just follow the 3D slicer's website, and fail to build the qt.

I have already try this qt-easy-build for several times, always failed, please help me.
The problem is 
jom: C:\D\Support\qt-4.8.7-64-vs2013-rel\src\3rdparty\webkit\Source\WebCore\Make
file.WebKit [release] Error 2
jom: C:\D\Support\qt-4.8.7-64-vs2013-rel\src\3rdparty\webkit\Source\Makefile.Web
Kit [sub-WebCore-make_default-ordered] Error 2
jom: C:\D\Support\qt-4.8.7-64-vs2013-rel\Makefile [sub-webkit-make_default-order
ed] Error 2
CMake Error at QEBQt4ExternalProjectCommand.cmake:123 (message):
  Problem building Qt
CMake Error at build_qt_with_openssl.cmake:197 (message):

Don't know why, and I want to know how to use the qt-easy-build 4.8.7.zip,I download it, and do not know the step to use it.
Please help me!

**Comment by jcfr** [comment]
Thanks for the report.

Closing. Issue is being discussed in #19 

More specifically https://github.com/jcfr/qt-easy-build/issues/19#issuecomment-209494129
