### ISSUE TITLE
Extend the script to support Linux and MacOSX

### ISSUE THREAD

**Issue by jcfr** [commontk/qt-easy-build#2]
- [ ] add `linux_build_qt.sh`
- [ ] add `macosx_build_qt.sh`

**Comment by jcfr** [comment]
Consider:
- project https://github.com/dlrdave/QtBuilder from @dlrdave 
- https://github.com/jcfr/qt-easy-build/blob/4.8.7/Build-qt.txt

**Comment by jcfr** [comment]
xref #15

**Comment by dlrdave** [comment]
Ah ha! Hi JC!

Looks like I need to update that to account for some new Qt version numbers again.

**Comment by jcfr** [comment]
Cc: @fbudin69500

**Comment by jcfr** [comment]
Closing. Thanks to @fbudin69500, `Build-qt.sh` was added  in July 2016 to build Qt 4 or Qt 5 on macOS and Linux
