### ISSUE TITLE
jom archive seems to be down - use mirrors?

### ISSUE THREAD

**Issue by gordon-n-stevenson** [commontk/qt-easy-build#22]
Tried to run this today but came across an error in getting jom from the Qt servers - a list of alternative mirrors can be found here and once manually installed worked a treat.

https://download.qt.io/official_releases/jom/jom_1_1_0.zip.mirrorlist

**Comment by jcfr** [comment]
@gordon-n-stevenson Thanks for the report. 

Using a more stable URL makes sense. 

Would you mind submitted a PR ?
