### ISSUE TITLE
Qt-easy-build script does not work for Sierra OSX

### ISSUE THREAD

**Issue by bpaniagua** [commontk/qt-easy-build#27]
Apple’s (Quicktime) QTKit framework has been removed in Sierra OSX. Running this script will fail after producing this error

../../../3rdparty/phonon/qt7/quicktimevideoplayer.h:23:9: fatal error: 'QTKit/QTDataReference.h' file not found

**Comment by jcfr** [comment]
Thanks for reporting the problem.

Is there any patch that could be applied to the Qt source ? Or option that could be disabled ? Is phonon required on MacOSX ?

**Comment by bpaniagua** [comment]
There is not a way to explicitly de-activate QTkit while compiling Qt4 (http://doc.qt.io/qt-4.8/configure-options.html). Homebrew developers point to the following pull request that has not been yet accepted (https://github.com/Homebrew/homebrew-core/pull/5216) as a way to de-activate phonon. I tried unsuccessfully to use this branch and compile Qt4 with homebrew  http://massmail.spl.harvard.edu/public-archives/slicer-devel/2016/040871.html.

The main question here is: (a) do we try to make qt4 workable for Sierra or (b) we just wait until Slicer has been ported to Qt5 and work with older OSX versions in the meantime?

**Comment by msmolens** [comment]
This may be fixed in #32 by https://github.com/jcfr/qt-easy-build/pull/32/commits/2ae06199c5aa79eea2b903abb4f3f58860022ec9. I tested building on El Capitan (10.11), but targeting the 10.12 SDK.

**Comment by jcfr** [comment]
Closing. This issue is obsolete. The minimum macOS version supported by 5.15.2 is macOS 10.13 (High Sierra).

See https://doc.qt.io/qt-5/macos.html#supported-versions
