### ISSUE TITLE
running qt-easy-build.sh does not produce frameworks on MacOSX 10.11

### ISSUE THREAD

**Issue by hina-shah** [commontk/qt-easy-build#31]
However, running commands step by step from qt-easy-build.txt works just fine and seems to be creating all the components correctly.

**Comment by jcfr** [comment]
Closing. This issue is obsolete. The minimum macOS version supported by 5.15.2 is macOS 10.13 (High Sierra).

See https://doc.qt.io/qt-5/macos.html#supported-versions
