### ISSUE TITLE
I have tried some times to build qt4.8.7,but there is always a mistake and I don't know how to do .I need your help jcfr!

### ISSUE THREAD

**Issue by barony14** [commontk/qt-easy-build#35]

**Comment by jcfr** [comment]
Sorry to hear it is not working out for you.

Without more context, it will be difficult to help you out.

On which platform ? What are all the steps leading to the error ? 

Ideally, your answer would be of the form:

1) Open Git Bash: `git clone git://github.com/jcfr/qt-easy-build -b 4.8.7`

2) Open Visual Studio terminal: 

_Indicate with 32-bit or 64-bit one, also indicate with version of visual studio_

3) Run build command: 

_Indicate which command you executed_

4) Report the error

**Comment by barony14** [comment]
Thank you . I build qt using win7(64)+vs2013(update5). The screenshot was not uploaded successfully.
The problem is as following:
 download 7zip commandline tool
 download http....
raw=true
when using '2' parameter calls 'downloadfile' ,an error occurs:'the underlying connection was closed':An error occurred while sending

**Comment by jcfr** [comment]
Here is the code causing trouble:

```
$downloader = new-object System.Net.WebClient
$url = 'https://github.com/chocolatey/chocolatey/blob/master/src/tools/7za.exe?raw=true'
$downloader.DownloadFile($url)
```

I just tried on a windows machine and I was able to reproduce.

Look like it is related to use of powershell to download from url accepting only newer TLS. See https://github.com/chocolatey/choco/wiki/Installation#installing-with-restricted-tls

**Comment by jcfr** [comment]
Also here is an useful script to find out which version of `.NET` are installed in your environment: https://stackoverflow.com/a/3495491/1539918

**Comment by jcfr** [comment]
I suggest to install the latest version of `.NET`. See https://www.microsoft.com/net/download/dotnet-framework-runtime/net471

**Comment by barony14** [comment]
I am trying your advice,thank you very much!

**Comment by jcfr** [comment]
To follow up on this, installing a newer .NET was not enough, you need to install the Windows Management Framework 4.0. See https://social.technet.microsoft.com/wiki/contents/articles/21016.how-to-install-windows-powershell-4-0.aspx

The version installed is now 4.x instead of 2.x:
```
PS C:\Users\dashboard> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
```

Them, trying to download report an error message but this time is more specific, it clearly indicate that it _Could not create SSL/TLS secure channel_:

```
PS C:\Users\dashboard> $downloader = new-object System.Net.WebClient
PS C:\Users\dashboard> $url = 'https://github.com/chocolatey/chocolatey/blob/master/src/tools/7za.exe?raw=true'
PS C:\Users\dashboard> $file = '7za.exe'
PS C:\Users\dashboard> $downloader.DownloadFile($url, $file)
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At line:1 char:1
+ $downloader.DownloadFile($url, $file)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

Finally, after setting the security protocol first, the download succeed:

```
$securityProtocolSettingsOriginal = [System.Net.ServicePointManager]::SecurityProtocol

try {
  # Set TLS 1.2 (3072), then TLS 1.1 (768), then TLS 1.0 (192), finally SSL 3.0 (48)
  # Use integers because the enumeration values for TLS 1.2 and TLS 1.1 won't
  # exist in .NET 4.0, even though they are addressable if .NET 4.5+ is
  # installed (.NET 4.5 is an in-place upgrade).
  [System.Net.ServicePointManager]::SecurityProtocol = 3072 -bor 768 -bor 192 -bor 48
} catch {
  Write-Warning 'Unable to set PowerShell to use TLS 1.2 and TLS 1.1 due to old .NET Framework installed. If you see underlying connection closed or trust errors, you may need to do one or more of the following: (1) upgrade to .NET Framework 4.5 and PowerShell v3, (2) specify internal Chocolatey package location (set $env:chocolateyDownloadUrl prior to install or host the package internally), (3) use the Download + PowerShell method of install. See https://chocolatey.org/install for all install options.'
}


$downloader = new-object System.Net.WebClient
$url = 'https://github.com/chocolatey/chocolatey/blob/master/src/tools/7za.exe?raw=true'
$file = '7za.exe'
$downloader.DownloadFile($url, $file)

[System.Net.ServicePointManager]::SecurityProtocol = $securityProtocolSettingsOriginal
```

I will update the FAQ accordingly and also update the powershell download function to update the `securityProtocolSettings`.

**Comment by barony14** [comment]
thank you very much. I have successfully compiled the source code.
