### ISSUE TITLE
Build Qt 4.8.7 Ubuntu 16.04 LTS Fail

### ISSUE THREAD

**Issue by deaspo** [commontk/qt-easy-build#39]
Am building qt4.8.7 on Ubuntu 16.04 LHS and am getting the following error when compiling rendering/RenderVideo.cpp
![qt_error](https://user-images.githubusercontent.com/10347760/38782316-e6f7936c-40f1-11e8-9fd7-d2cf4df27ffb.PNG)

See the message from attached. AM running Ubuntu as VM. Any help on this will be appreciated

**Comment by jcfr** [comment]
Thanks for the report 🙏 and our apologies for the late follow up.

Closing as current maintenance are geared toward maintaining build for Qt 5.15.1 on Linux and macOS.

That said, contributions are welcome.
