### ISSUE TITLE
Script fails to build on MSVC2012

### ISSUE THREAD

**Issue by finetjul** [commontk/qt-easy-build#4]
Chocolatey fails to install strawberryperl

**Comment by jcfr** [comment]
Could you try the 4.8.6  branch ?

##

**Comment by finetjul** [comment]
indeed, the branch 4.8.6 goes a bit further. 
Nonetheless, vs2012 was not supported. I added support here:
- https://github.com/finetjul/qt-easy-build/tree/4.8.6

However a file (hashset.h in webkit) must still be patched:
- http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Build_Instructions/Prerequisites/Qt#Qt_4.8.6_.2F_VS2012

**Comment by jcfr** [comment]
Thanks.

Fixed in b85a388de65334abe154ae4a24395ff239b92b74
