### ISSUE TITLE
Silent failure to build QtWebEngine on Linux?

### ISSUE THREAD

**Issue by ihnorton** [commontk/qt-easy-build#40]
The build script seems to silently proceed when QtWebEngine prerequisites are not met. It would be nice to enforce some checking at least for Slicer builds. Do you know if there is a way to enforce this in the Qt build system?

**Comment by ihnorton** [comment]
btw the most up-to-date set of prereq instructions I've found is here:

https://wiki.qt.io/Building_Qt_5_from_Git#Linux.2FX11

**Comment by ihnorton** [comment]
:( Seems like a known issue -- homebrew has had the same problem:

> Silently skipping QtWebEngine during the build because some additional requirement isn't met is more than just surprising.

https://github.com/Homebrew/homebrew-core/pull/2087#issuecomment-231960871

**Comment by ihnorton** [comment]
I asked on the mailing list, and response is:

> There's no such option.

-- http://lists.qt-project.org/pipermail/interest/2018-April/029850.html

**Comment by jcfr** [comment]
Closing. WebEngine now builds 


See https://github.com/jcfr/qt-easy-build/commit/756c6e5a830585e3bc0214c3d99b87404fb55e7c and https://github.com/jcfr/qt-easy-build/pull/41#issuecomment-700860334
