### ISSUE TITLE
Ld trying to use system install of Qt5

### ISSUE THREAD

**Issue by tavaughan** [commontk/qt-easy-build#42]
I ran the Build-qt.sh script for Qt 5.10.0 in Pop_OS (based on Ubuntu 17.10). I then tried to build a program called 3D Slicer using my local build of Qt5. I got a confusing error:

> /media/vaughan/workspace/lnx/devel/Support/qt-everywhere-build-5.10.0/bin/uic: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.10’ not found (required by /media/vaughan/workspace/lnx/devel/Support/qt-everywhere-build-5.10.0/bin/uic)

It looks as though ld was looking for a system build of Qt for some reason? See related discussion here: https://discourse.slicer.org/t/compile-errors-pop-os-with-qt-5-10/2576/15

At least one other person had the same issue in Ubuntu 18.04.

I was able to fix the problem by changing the Build-Qt.sh script. I changed the "-no-rpath" option to "-rpath" (not sure if this is the same as simply not having "-no-rpath").

Could this an issue with the script and recent versions of Ubuntu?

**Comment by ihnorton** [comment]
@tavaughan that change is correct for Linux. I believe the change was made for mac (see [here](https://discourse.slicer.org/t/transition-of-nightly-build-to-qt5-vtk9-cmake-3-9-and-c-11/1918/15)), and no one noticed the issue on Linux because the Slicer launcher sets the needed LD_LIBRARY_PATH in the distribution package.

Do you want to submit a pull-request? It should be `-no-rpath` on `Darwin` only for now (there's some examples how to check in the script).

**Comment by ihnorton** [comment]
(Just to add: you won't be able to build a redistributable package with such Qt right now)

**Comment by tavaughan** [comment]
Sure, I forked and made commit: https://github.com/tavaughan/qt-easy-build/commit/ef849b281b7dfea46a0a5c3789e452c1e9b4ac60

But this will take a while for me to test because of the build times involved. Should I wait until I know it works on Linux before creating pull request?

**Comment by ihnorton** [comment]
My build succeeded with that patch (just removing `-no-rpath`, the Darwin check looks good), but aside from checking that the GUI starts I can't test very much right now because it is a remote machine with limited graphics.

**Comment by tavaughan** [comment]
I tried to build overnight on a personal laptop. Qt has finished building. Slicer hasn't. I'll update here again tomorrow.

**Comment by tavaughan** [comment]
It builds in Slicer, I don't seem to be having any major issues. I note a few warnings on startup but I don't think they are related.

```
Traceback (most recent call last):
  File "/media/vaughan/workspace/lnx/devel/S4D/Slicer-build/lib/Slicer-4.9/qt-scripted-modules/DMRIInstall.py", line 60, in __init__
    model = slicer.app.extensionsManagerModel()
AttributeError: qSlicerApplication has no attribute named 'extensionsManagerModel'
```
```
qSlicerPythonCppAPI::instantiateClass  - [ "DMRIInstall" ] - Failed to instantiate scripted pythonqt class "DMRIInstall" 0x7fd7707bb600
Fail to instantiate module  "DMRIInstall"
```
```
QObject::connect: No such slot qSlicerApplication::openExtensionsManagerDialog() in /media/vaughan/workspace/lnx/devel/S4/Modules/Loadable/SlicerWelcome/qSlicerWelcomeModuleWidget.cxx:94
QObject::connect:  (sender name:   'OpenExtensionsManagerButton')
```

**Comment by tavaughan** [comment]
(I had -DSlicer_BUILD_EXTENSIONMANAGER_SUPPORT:BOOL=OFF)

**Comment by jcfr** [comment]
> I note a few warnings on startup but I don't think they are related.

These are now tracked in https://issues.slicer.org/view.php?id=4574

**Comment by jcfr** [comment]
@tavaughan  Now that #43 has been merged, can this be closed ?

**Comment by tavaughan** [comment]
Yes
