### ISSUE TITLE
Qt5.10.0 build error

### ISSUE THREAD

**Issue by bluels** [commontk/qt-easy-build#44]
hi, i need to build qt5 to try the slicervirtualreality. But i use the command below, it still download the qt-everywhere-opensource-src-4.8.7.zip  , not the 5.10.0, what should i do? Really thanks!

```
@powershell -Command "$destDir='C:\D\Support';$buildType='Debug';$qtPlatform='win32-msvc2013';$bits='64';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/jcfr/qt-easy-build/5.10.0/windows_build_qt.ps1'))"
```

Environments:
Visual Studio: 2013, Update 5 
OS：Win10 64

**Comment by jcfr** [comment]
Closing. We will not fix this. See https://github.com/jcfr/qt-easy-build/pull/28#issuecomment-700855044
