### ISSUE TITLE
Readme Windows part need update for Qt5 branches

### ISSUE THREAD

**Issue by idhamari** [commontk/qt-easy-build#49]
An example 5.11.2 branch still using VS2013 and Qt-4.8.7:

      @powershell -Command "$destDir='C:\D\Support';$buildType='Release';$qtPlatform='win32-msvc2013';$bits='64';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/jcfr/qt-easy-build/4.8.7/windows_build_qt.ps1'))"

**Comment by jcfr** [comment]
A disclaimer mentioning building Qt 5.15 on windows using this project is not yet supported.

Created a dedicated issue:
* https://github.com/jcfr/qt-easy-build/issues/71
