### ISSUE TITLE
QT 4.8.5 download is no longer available

### ISSUE THREAD

**Issue by blowekamp** [commontk/qt-easy-build#5]
I tried running the current script in master and I am getting a failed download of: http://download.qt-project.org/official_releases/qt/4.8/4.8.5/qt-everywhere-opensource-src-4.8.5.zip 4.8.5 appear to no longer be hosted.

I am trying the script in the 4.8.6 branch now...

**Comment by jcfr** [comment]
Default branch has been changed from `4.8.5` to `4.8.6`

Master branch has been renamed into `4.8.5`
