### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by ayasns** [commontk/qt-easy-build#50]
Hi could u help me please.
i need to use your static release qt 5.11.2 x86 and when i use it with visual studio 2017.
first i select it and make it default in VS Qt addons and change linker optimization option to /LTCG
and when i compile any simple code just print hello c++ it show me error:-
fatal error c1007 unrecognized flag '-Os' in 'p2'
 how i can fix that error please help

**Comment by jcfr** [comment]
Closing. The build scripts are not intended to support building Qt statically.

To build Qt statically, consider looking at:
* https://github.com/jcfr/qt5-minimalistic-builds/blob/add-msvc-build5112-static-x86-applauncher/msvc-build5112-static-x86.ps1
* https://gist.github.com/mrfaptastic/80e909c9a8237994471bce2d17657779 

and similar resources found via internet searching.
