### ISSUE TITLE
building over Ubuntu 18 - problem finding qmake configuration file

### ISSUE THREAD

**Issue by GalKer** [commontk/qt-easy-build#51]
Hi, 
Running over ubuntu 18.04 passed the zlib and openSSL phases and failing at the "Build Qt":

Build Qt
+ cd qtbase
+ /home/qt-easy-build/qt-easy-build/qt-everywhere-src-5.10.0/qtbase/configure -top-level -prefix /home/qt-easy-build/qt-easy-build/qt-everywhere-build-5.10.0 -release -opensource -confirm-license -c++std c++11 -nomake examples -nomake tests -silent -openssl -I /home/qt-easy-build/qt-easy-build/qt-everywhere-deps-5.10.0/openssl-1.0.2n/include -L /home/qt-easy-build/qt-easy-build/qt-everywhere-deps-5.10.0/openssl-1.0.2n
Creating qmake...
.Done.
**Could not find qmake configuration file .**
Error processing project file: /home/qt-easy-build/qt-easy-build/qt-everywhere-src-5.10.0

Could you advise what I should configure/where?

Kind regards,
Gal

**Comment by jcfr** [comment]
Closing. Scripts are now expected to build Qt 5.15.x on more recent Ubuntu like 20.04 and 22.04
