### ISSUE TITLE
Add support for building Qt 5.15.2

### ISSUE THREAD

**Issue by jcfr** [commontk/qt-easy-build#62]
* [x] Create branch 5.15.2. 
* [x] Update README moving 5.15.1 to unmaintained list (https://github.com/jcfr/qt-easy-build/pull/63)
* [x] Update CI to build 5.15.2
* [ ] Update script to support building for Big  Sur (https://github.com/jcfr/qt-easy-build/issues/61)

@jamesobutler Do you know what is the status on Azure Pipeline ?

cc: @piiq

**Comment by jamesobutler** [comment]
@jcfr From my recollection the next steps for the Azure Pipeline work in this repo was that I needed you to go into Settings->Integrations for this repo and make sure you have the Azure Pipeline GitHub app installed with repository access.  Can you do that for me?

The Azure Pipeline repo was set up over at https://dev.azure.com/jchrisfillionr/qt-easy-build.

**Comment by jamesobutler** [comment]
I included d9ae8b83ac08dc8dce4d655a98323f43db431a97 as part of the new [`5.15.2`](https://github.com/jcfr/qt-easy-build/tree/5.15.2) branch, but azure pipelines reports a build issue https://dev.azure.com/jchrisfillionr/qt-easy-build/_build/results?buildId=2&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=8ef82b3b-1feb-5bbd-06f6-b1f7b5467f03

> ERROR: Unknown command line option '-no-xinerama'

See [QTBUG-89364: Configure -no-xinerama doesn't work](https://bugreports.qt.io/browse/QTBUG-89364)

**Comment by jcfr** [comment]
> next steps for the Azure Pipeline work in this repo was that I needed you to go into Settings->Integrations for this repo and make sure you have the Azure Pipeline GitHub app installed with repository access

This should be good now.

> ERROR: Unknown command line option '-no-xinerama'

Out of curiosity, is this error new with `5.15.2` ? Was this option available with 5.15.1 but having no effect ?

**Comment by jamesobutler** [comment]
The original Qt bug report was issued by someone having issues with it using 5.15.1 so I'm guessing it wasn't an option then either. Seems like the documentation was not correct from briefly looking into that text.

When you tried with Qt 5.15.1 as part of #60 did it work?

**Comment by jamesobutler** [comment]
A more detailed thread about xinerama https://bugreports.qt.io/browse/QTBUG-84749

In general seems like Qt has taken the approach of the user making sure they have certain dependencies. Meaning likely their -no flag hasn’t been maintained and is not working.

**Comment by jcfr** [comment]
Support for building without xinerama is now tracked in a dedicated issue:
* https://github.com/jcfr/qt-easy-build/issues/65
